AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'bin/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
