version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps

  checking:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspection with Rubocop

  test:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
